/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Travelling;

import java.awt.print.PrinterException;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rezwan
 */
public class Travels extends javax.swing.JFrame {

    double gross;
    cFlight cost=new cFlight();
    
    
    
    
    
    public Travels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        postcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jrbsingle = new javax.swing.JRadioButton();
        jrbstandard = new javax.swing.JRadioButton();
        jrbeconomy = new javax.swing.JRadioButton();
        jrbfirstclass = new javax.swing.JRadioButton();
        jrbreturn = new javax.swing.JRadioButton();
        jlblstandard = new javax.swing.JLabel();
        jlbleconomy = new javax.swing.JLabel();
        jlblsingle = new javax.swing.JLabel();
        jlblreturn = new javax.swing.JLabel();
        jlblfirstclass = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jcmbaccomodation = new javax.swing.JComboBox<>();
        jcmbdeparture = new javax.swing.JComboBox<>();
        jcmbdestination = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblsubtotal = new javax.swing.JLabel();
        jlbltax = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipt = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnexit = new javax.swing.JButton();
        jbtntotal = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnrecipt = new javax.swing.JButton();
        print = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel2.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Surname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel2.add(postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Post Code");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel2.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbsingle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbsingle.setText("Single");
        jPanel3.add(jrbsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jrbstandard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbstandard.setText("Standard");
        jrbstandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbstandardActionPerformed(evt);
            }
        });
        jPanel3.add(jrbstandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jrbeconomy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbeconomy.setText("Economy");
        jrbeconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbeconomyActionPerformed(evt);
            }
        });
        jPanel3.add(jrbeconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jrbfirstclass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbfirstclass.setText("First Class");
        jrbfirstclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbfirstclassActionPerformed(evt);
            }
        });
        jPanel3.add(jrbfirstclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jrbreturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbreturn.setText("Return");
        jPanel3.add(jrbreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jlblstandard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblstandard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblstandard.setText("0");
        jlblstandard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jlblstandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        jlbleconomy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbleconomy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbleconomy.setText("0");
        jlbleconomy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jlbleconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 30));

        jlblsingle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsingle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblsingle.setText("0");
        jlblsingle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jlblsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 30));

        jlblreturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblreturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblreturn.setText("0");
        jlblreturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jlblreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, 30));

        jlblfirstclass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblfirstclass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblfirstclass.setText("0");
        jlblfirstclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jlblfirstclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 420, 230));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Accomodation");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Destination");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Departure");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox2.setText("Tax");
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jcmbaccomodation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbaccomodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Single", "Double", "Extra" }));
        jPanel4.add(jcmbaccomodation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jcmbdeparture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbdeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dhaka", "Chittagong", "Rajshahi", "Sylhet", "Comilla", " " }));
        jPanel4.add(jcmbdeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jcmbdestination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbdestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Cox- Bazar - 3 Days", "St. Martin's Island - 2 Days", "Nilgiri - 2 Days", "Sundarbans Tour - 1 Day", "Sundarbans Tour - 3 Days", "Sylhet (Ratargul-Bisanakand)-2 Days", "Sylhet (Jaflong-Dargah Shariff)-2 Days", "Sylhet (All) - 4 Days" }));
        jcmbdestination.setEnabled(false);
        jcmbdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbdestinationActionPerformed(evt);
            }
        });
        jPanel4.add(jcmbdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 310, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Sub Total");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Tax");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jlblsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlblsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, 30));

        jlbltax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbltax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlbltax, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 30));

        jlbltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbltotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 130, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 240, 140));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recipt.setColumns(20);
        recipt.setRows(5);
        jScrollPane1.setViewportView(recipt);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 370));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Recipt");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 280, 410));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 100, 40));

        jbtntotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtntotal.setText("Total");
        jbtntotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jbtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntotalActionPerformed(evt);
            }
        });
        jPanel7.add(jbtntotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jbtnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, 40));

        jbtnrecipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnrecipt.setText("Recipt");
        jbtnrecipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnrecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnreciptActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnrecipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, 40));

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("Print");
        print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel7.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, 40));

        savebutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savebutton.setText("Save File");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel7.add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 71, -1, 40));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 530, 120));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TRAVEL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        cQuit cExit= new cQuit();
        
        cExit.quit();
        
        
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntotalActionPerformed
        
        
        
        
        cCostTax iTax = new cCostTax();
        double iTaxes,subtotal;
        
        if(jrbreturn.isSelected())
        {
            subtotal=gross*2;
            String isubtotal=String.format("%.2f", subtotal);
            
            jlblsubtotal.setText(isubtotal);
            iTaxes= iTax.cFindTax(subtotal);
            
            String tax=String.format("%.2f", iTaxes);
            jlbltax.setText(tax);
            
            String iTotal=String.format("%.2f", subtotal+ iTaxes);
            jlbltotal.setText(iTotal); 
            
            jlblreturn.setText(isubtotal);
        }
        else
        {
            subtotal=gross;
            String isubtotal=String.format("%.2f", subtotal);
            
            jlblsubtotal.setText(isubtotal);
            iTaxes= iTax.cFindTax(subtotal);
            
            String tax=String.format("%.2f", iTaxes);
            jlbltax.setText(tax);
            
            String iTotal=String.format("%.2f", subtotal+ iTaxes);
            jlbltotal.setText(iTotal);
        }
        
        
        
    }//GEN-LAST:event_jbtntotalActionPerformed

    private void jcmbdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbdestinationActionPerformed


        
        
        if ((jcmbdestination.getSelectedItem().equals("Cox- Bazar - 3 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Cox;
            String Cost= String.format("%.2f", cost.Cox);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("St. Martin's Island - 2 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.St_Martin;
            String Cost= String.format("%.2f", cost.St_Martin);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Nilgiri - 2 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Nilgiri;
            String Cost= String.format("%.2f", cost.Nilgiri);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 1 Day")) &&jrbstandard.isSelected())
        {
            gross=cost.Sundarbans_1;
            String Cost= String.format("%.2f", cost.Sundarbans_1);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 3 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Sundarbans_3;
            String Cost= String.format("%.2f", cost.Sundarbans_3);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Ratargul-Bisanakand)-2 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Sylhet_R_B;
            String Cost= String.format("%.2f", cost.Sylhet_R_B);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Jaflong-Dargah Shariff)-2 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Sylhet_Jaflong;
            String Cost= String.format("%.2f", cost.Sylhet_Jaflong);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (All) - 4 Days")) &&jrbstandard.isSelected())
        {
            gross=cost.Sylhet_All;
            String Cost= String.format("%.2f", cost.Sylhet_All);
            jlblstandard.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        
        /////////////////////////////////////////////////////////////////////////////////////////////////
        
        if ((jcmbdestination.getSelectedItem().equals("Cox- Bazar - 3 Days")) &&jrbeconomy.isSelected())
        {
            gross=cost.Cox;
            String Cost= String.format("%.2f", cost.Cox+900);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        
        if ((jcmbdestination.getSelectedItem().equals("St. Martin's Island - 2 Days")) &&jrbeconomy.isSelected())
        {
            gross=cost.St_Martin;
            String Cost= String.format("%.2f", cost.St_Martin+1200);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Nilgiri - 2 Days")) &&jrbeconomy.isSelected())
        {
            gross=cost.Nilgiri;
            String Cost= String.format("%.2f", cost.Nilgiri+1500);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 1 Day")) &&jrbeconomy.isSelected())
        {
            gross=cost.Sundarbans_1;
            String Cost= String.format("%.2f", cost.Sundarbans_1+990);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 3 Days")) &&jrbeconomy.isSelected())
        {
            
            gross=cost.Sundarbans_3;
            String Cost= String.format("%.2f", cost.Sundarbans_3+890);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Ratargul-Bisanakand)-2 Days")) &&jrbeconomy.isSelected())
        {
            gross=cost.Sylhet_R_B;
            String Cost= String.format("%.2f", cost.Sylhet_R_B+1050);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Jaflong-Dargah Shariff)-2 Days")) &&jrbeconomy.isSelected())
        {
            gross=cost.Sylhet_Jaflong;
            String Cost= String.format("%.2f", cost.Sylhet_Jaflong+1500);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (All) - 4 Days")) &&jrbeconomy.isSelected())
        {
            
            gross=cost.Sylhet_All;
            String Cost= String.format("%.2f", cost.Sylhet_All+3000);
            jlbleconomy.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        
        
        ////////////////////////////////////////////////////////////////////////////////////////////////
        
        if ((jcmbdestination.getSelectedItem().equals("Cox- Bazar - 3 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Cox;
            String Cost= String.format("%.2f", cost.Cox+3500);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        
        if ((jcmbdestination.getSelectedItem().equals("St. Martin's Island - 2 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.St_Martin;
            String Cost= String.format("%.2f", cost.St_Martin+2500);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Nilgiri - 2 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Nilgiri;
            String Cost= String.format("%.2f", cost.Nilgiri+2500);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 1 Day")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Sundarbans_1;
            String Cost= String.format("%.2f", cost.Sundarbans_1+1900);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sundarbans Tour - 3 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Sundarbans_3;
            String Cost= String.format("%.2f", cost.Sundarbans_3+2500);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Ratargul-Bisanakand)-2 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Sylhet_R_B;
            String Cost= String.format("%.2f", cost.Sylhet_R_B+3500);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (Jaflong-Dargah Shariff)-2 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Sylhet_Jaflong;
            String Cost= String.format("%.2f", cost.Sylhet_Jaflong+9600);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        if ((jcmbdestination.getSelectedItem().equals("Sylhet (All) - 4 Days")) &&jrbfirstclass.isSelected())
        {
            gross=cost.Sylhet_All;
            String Cost= String.format("%.2f", cost.Sylhet_All+9600);
            jlblfirstclass.setText(Cost);
            jlblsingle.setText(Cost);
            jrbsingle.setSelected(true);
        }
        
        
        
        


    }//GEN-LAST:event_jcmbdestinationActionPerformed

    private void jrbstandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbstandardActionPerformed
        
        if (jrbstandard.isSelected()==true)
        {
            jcmbdestination.setEnabled(true);
            jrbeconomy.setSelected(false);
            jrbfirstclass.setSelected(false);
            jlbleconomy.setText("0");
            jlblfirstclass.setText("0");
            jlblsingle.setText("0");
            jlblreturn.setText("0");
            
        }
        
        if (jrbstandard.isSelected()==false)
        {
            jcmbdestination.setSelectedItem("None");
            jcmbdestination.setEnabled(false);
            jlblstandard.setText("0");
        }
    }//GEN-LAST:event_jrbstandardActionPerformed

    private void jrbeconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbeconomyActionPerformed
        
        if (jrbeconomy.isSelected()==true)
        {
            jcmbdestination.setEnabled(true);
            jrbstandard.setSelected(false);
            jrbfirstclass.setSelected(false);
            jlblstandard.setText("0");
            jlblfirstclass.setText("0");
            jlblsingle.setText("0");
            jlblreturn.setText("0");
            
        }
        
        if (jrbeconomy.isSelected()==false)
        {
            jcmbdestination.setSelectedItem("None");
            jcmbdestination.setEnabled(false);
            jlbleconomy.setText("0");
        }
        
        
    }//GEN-LAST:event_jrbeconomyActionPerformed

    private void jrbfirstclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbfirstclassActionPerformed
        
        if (jrbfirstclass.isSelected()==true)
        {
            jcmbdestination.setEnabled(true);
            jrbeconomy.setSelected(false);
            jrbstandard.setSelected(false);
            jlblstandard.setText("0");
            jlbleconomy.setText("0");
            jlblsingle.setText("0");
            jlblreturn.setText("0");
            
        }
        
        if (jrbfirstclass.isSelected()==false)
        {
            jcmbdestination.setSelectedItem("None");
            jcmbdestination.setEnabled(false);
            jlblfirstclass.setText("0");
        }
        
        
    }//GEN-LAST:event_jrbfirstclassActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
       
        firstname.setText(null);
        surname.setText(null);
        address.setText(null);
        email.setText(null);
        mobile.setText(null);
        postcode.setText(null);
        jlbltax.setText(null);
        jlblsubtotal.setText(null);
        jlbltotal.setText(null);
        recipt.setText(null);
        
        jlblfirstclass.setText("0");
        jlblsingle.setText("0");
        jlblreturn.setText("0");
        jlbleconomy.setText("0");
        jlblstandard.setText("0");
        
        jcmbdeparture.setSelectedItem("None");
        jcmbdestination.setSelectedItem("None");
        jcmbaccomodation.setSelectedItem("None");
        jrbstandard.setSelected(false);
        jrbeconomy.setSelected(false);
        jrbfirstclass.setSelected(false);
        jrbsingle.setSelected(false);
        jrbreturn.setSelected(false);
        
       
        
        
        
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnreciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreciptActionPerformed
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat ("HH:mm:ss");
        String iTime = (tTime.format(timer.getTime()));
        
        SimpleDateFormat TDate = new SimpleDateFormat ("dd:MM:yyyy");
        String iDate = (TDate.format(timer.getTime()));
        
                    int num1;
                    String ref="";
                    num1 = 1325 +(int) (Math.random()*4238);
                    ref += num1 + 1325;
                    
        String Firstname = (firstname.getText());
        String Surname = (surname.getText());
        String Address = (address.getText());
        String Postcode = (postcode.getText());
        String Mobile = (mobile.getText());
        String rTax = (jlbltax.getText());
        String rSubtotal = (jlblsubtotal.getText());
        String rTotal = (jlbltotal.getText());
        String Email = (email.getText()); 
        String destination=(jcmbdestination.getSelectedItem().toString());
        String accomodation=(jcmbaccomodation.getSelectedItem().toString());
        String Departure=(jcmbdeparture.getSelectedItem().toString());
                    
            recipt.append("Travel Management System:\n\n"
                +"Ref\t:"+ ref
                +"\n-----------------------------------------------------------------"
                +"\nName\t:    "+Firstname
                +"\nSurname\t:    "+Surname
                +"\nAddress\t:    "+Address
                +"\nPostcode\t:    "+Postcode
                +"\nMobile\t:    "+Mobile
                +"\nE-Mail\t:    "+Email
                +"\nDeparture\t:    "+Departure
                +"\nDestination\t:    "+destination
                +"\nAccomodation\t:    "+accomodation
                +"\nTax\t:    "+rTax
                +"\nSub Total\t:    "+rSubtotal
                +"\nTotal\t:    "+rTotal
                +"\n-----------------------------------------------------------------"
                +"\nDate:\t"+iDate+"\tTime:"+iTime
                +"\n\nThanks for Using \nTravel Management System"
        );        
                    
        
        
        
    }//GEN-LAST:event_jbtnreciptActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       try{
            
            recipt.print();
        }
                catch (PrinterException ex){
                    Logger.getLogger(Travels.class.getName()).log(Level.SEVERE,null, ex);
                }
    }//GEN-LAST:event_printActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
       
        String Firstname = (firstname.getText());
        String Surname = (surname.getText());
        String Address = (address.getText());
        String Postcode = (postcode.getText());
        String Mobile = (mobile.getText());
        String rTax = (jlbltax.getText());
        String rSubtotal = (jlblsubtotal.getText());
        String rTotal = (jlbltotal.getText());
        String Email = (email.getText()); 
        String destination=(jcmbdestination.getSelectedItem().toString());
        String accomodation=(jcmbaccomodation.getSelectedItem().toString());
        String Departure=(jcmbdeparture.getSelectedItem().toString());
        
        try {
            
            FileWriter writer =new FileWriter("file.txt",true);
            writer.write("NAME  "+Firstname);
            writer.write(System.getProperty("line.separator"));
            writer.write("Surname    "+Surname);
            writer.write(System.getProperty("line.separator"));
            writer.write("Address    "+Address);
            writer.write(System.getProperty("line.separator"));
            writer.write("Post Code    "+Postcode);
            writer.write(System.getProperty("line.separator"));
            writer.write("Mobile    "+Mobile);
            writer.write(System.getProperty("line.separator"));
            writer.write("Email    "+Email);
            writer.write(System.getProperty("line.separator"));
            writer.write("Destination    "+destination);
            writer.write(System.getProperty("line.separator"));
            writer.write("Accomodation    "+accomodation);
            writer.write(System.getProperty("line.separator"));
            writer.write("Departure    "+Departure);
            writer.write(System.getProperty("line.separator"));
            writer.write("Tax    "+rTax);
            writer.write(System.getProperty("line.separator"));
            writer.write("Subtotal    "+rSubtotal);
            writer.write(System.getProperty("line.separator"));
            writer.write("Total    "+rTotal);
            writer.write(System.getProperty("line.separator"));
            writer.close();
            JOptionPane.showMessageDialog(rootPane, "Successfull!!");  
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, "ERROR");
        }
        
        
    }//GEN-LAST:event_savebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnrecipt;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtntotal;
    private javax.swing.JComboBox<String> jcmbaccomodation;
    private javax.swing.JComboBox<String> jcmbdeparture;
    private javax.swing.JComboBox<String> jcmbdestination;
    private javax.swing.JLabel jlbleconomy;
    private javax.swing.JLabel jlblfirstclass;
    private javax.swing.JLabel jlblreturn;
    private javax.swing.JLabel jlblsingle;
    private javax.swing.JLabel jlblstandard;
    private javax.swing.JLabel jlblsubtotal;
    private javax.swing.JLabel jlbltax;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JRadioButton jrbeconomy;
    private javax.swing.JRadioButton jrbfirstclass;
    private javax.swing.JRadioButton jrbreturn;
    private javax.swing.JRadioButton jrbsingle;
    private javax.swing.JRadioButton jrbstandard;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField postcode;
    private javax.swing.JButton print;
    private javax.swing.JTextArea recipt;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
